<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Buku;
use Carbon\Carbon;

class BukuSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            // === FEATURED / POPULER (5 buku) ===
            [
                'kode_buku' => 'BK001',
                'isbn' => '9781250178633',
                'judul' => 'The Seven Husbands of Evelyn Hugo',
                'pengarang' => 'Taylor Jenkins Reid',
                'penerbit' => 'Washington Square Press',
                'tahun_terbit' => 2017,
                'kategori' => 'Fiction',
                'stok' => 5,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9781250178633-L.jpg',
                'deskripsi' => 'Aging Hollywood icon Evelyn Hugo tells the story of her glamorous life and seven marriages to a struggling magazine reporter. A tale of ambition, love, and the price of fame.',
                'rating' => 4.7,
                'is_featured' => true,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK002',
                'isbn' => '9780307744432',
                'judul' => 'The Night Circus',
                'pengarang' => 'Erin Morgenstern',
                'penerbit' => 'Anchor Books',
                'tahun_terbit' => 2011,
                'kategori' => 'Fantasy',
                'stok' => 4,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780307744432-L.jpg',
                'deskripsi' => 'Two young magicians are pitted against each other in a mysterious competition within a magical black-and-white circus. A mesmerizing tale of love and illusion.',
                'rating' => 4.5,
                'is_featured' => true,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK003',
                'isbn' => '9781250144171',
                'judul' => 'The Starless Sea',
                'pengarang' => 'Erin Morgenstern',
                'penerbit' => 'Anchor Books',
                'tahun_terbit' => 2019,
                'kategori' => 'Fantasy',
                'stok' => 3,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9781250144171-L.jpg',
                'deskripsi' => 'A graduate student discovers a mysterious book that leads him to a hidden underground library filled with stories. An enchanting world of love, loss, and stories within stories.',
                'rating' => 4.3,
                'is_featured' => true,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK004',
                'isbn' => '9780765387561',
                'judul' => 'The Invisible Life of Addie LaRue',
                'pengarang' => 'V.E. Schwab',
                'penerbit' => 'Tor Books',
                'tahun_terbit' => 2020,
                'kategori' => 'Fantasy',
                'stok' => 6,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780765387561-L.jpg',
                'deskripsi' => 'A young woman makes a Faustian bargain to live forever but is cursed to be forgotten by everyone she meets. Until one day, someone remembers her.',
                'rating' => 4.6,
                'is_featured' => true,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK005',
                'isbn' => '9781984896391',
                'judul' => 'A Good Girl\'s Guide to Murder',
                'pengarang' => 'Holly Jackson',
                'penerbit' => 'Delacorte Press',
                'tahun_terbit' => 2019,
                'kategori' => 'Mystery',
                'stok' => 4,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9781984896391-L.jpg',
                'deskripsi' => 'A high school student investigates a closed murder case for her senior project and uncovers dangerous truths. A gripping YA mystery thriller.',
                'rating' => 4.8,
                'is_featured' => true,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],

            // === WAITLIST (stok = 0) - 5 buku ===
            [
                'kode_buku' => 'BK006',
                'isbn' => '9781250750808',
                'judul' => 'The Atlas Six',
                'pengarang' => 'Olivie Blake',
                'penerbit' => 'Tor Books',
                'tahun_terbit' => 2022,
                'kategori' => 'Fantasy',
                'stok' => 0,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9781250750808-L.jpg',
                'deskripsi' => 'Six magicians are chosen to compete for a place in the most powerful secret society. Dark academia meets magical rivalry.',
                'rating' => 4.2,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 12,
            ],
            [
                'kode_buku' => 'BK007',
                'isbn' => '9780062060624',
                'judul' => 'The Song of Achilles',
                'pengarang' => 'Madeline Miller',
                'penerbit' => 'Ecco Press',
                'tahun_terbit' => 2012,
                'kategori' => 'Historical Fiction',
                'stok' => 0,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780062060624-L.jpg',
                'deskripsi' => 'The epic love story between Achilles and Patroclus during the Trojan War, retold with stunning prose. A heartbreaking tale of fate and devotion.',
                'rating' => 4.9,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 18,
            ],
            [
                'kode_buku' => 'BK008',
                'isbn' => '9781250857439',
                'judul' => 'Divine Rivals',
                'pengarang' => 'Rebecca Ross',
                'penerbit' => 'Wednesday Books',
                'tahun_terbit' => 2023,
                'kategori' => 'Romance',
                'stok' => 0,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9781250857439-L.jpg',
                'deskripsi' => 'Two rival journalists exchange anonymous letters during wartime, not knowing each other\'s true identity. A romantic fantasy with wartime stakes.',
                'rating' => 4.4,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 9,
            ],
            [
                'kode_buku' => 'BK009',
                'isbn' => '9780316556347',
                'judul' => 'Circe',
                'pengarang' => 'Madeline Miller',
                'penerbit' => 'Little, Brown and Company',
                'tahun_terbit' => 2018,
                'kategori' => 'Historical Fiction',
                'stok' => 0,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780316556347-L.jpg',
                'deskripsi' => 'The witch Circe tells her own story of exile, transformation, and finding power in a world of gods and heroes. Feminist retelling of Greek mythology.',
                'rating' => 4.5,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 15,
            ],
            [
                'kode_buku' => 'BK010',
                'isbn' => '9780142424179',
                'judul' => 'The Fault in Our Stars',
                'pengarang' => 'John Green',
                'penerbit' => 'Penguin Books',
                'tahun_terbit' => 2012,
                'kategori' => 'Young Adult',
                'stok' => 0,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780142424179-L.jpg',
                'deskripsi' => 'Two teens meet in a cancer support group and embark on a life-affirming journey together. A story about love, loss, and living fully.',
                'rating' => 4.6,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 21,
            ],

            // === BARU DIKEMBALIKAN (returned_at < 24 jam, stok terbatas) - 5 buku ===
            [
                'kode_buku' => 'BK011',
                'isbn' => '9780316769488',
                'judul' => 'The Catcher in the Rye',
                'pengarang' => 'J.D. Salinger',
                'penerbit' => 'Little, Brown and Company',
                'tahun_terbit' => 1951,
                'kategori' => 'Fiction',
                'stok' => 2,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg',
                'deskripsi' => 'A teenager\'s journey through New York City after being expelled from prep school. Classic coming-of-age story about alienation and identity.',
                'rating' => 4.0,
                'is_featured' => false,
                'returned_at' => Carbon::now()->subHours(2),
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK012',
                'isbn' => '9780143127550',
                'judul' => 'The Midnight Library',
                'pengarang' => 'Matt Haig',
                'penerbit' => 'Penguin Books',
                'tahun_terbit' => 2020,
                'kategori' => 'Fiction',
                'stok' => 1,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780143127550-L.jpg',
                'deskripsi' => 'Between life and death, Nora finds a library where each book represents a different life she could have lived. A story about regret, choices, and hope.',
                'rating' => 4.3,
                'is_featured' => false,
                'returned_at' => Carbon::now()->subHours(5),
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK013',
                'isbn' => '9780385490818',
                'judul' => 'The Kite Runner',
                'pengarang' => 'Khaled Hosseini',
                'penerbit' => 'Riverhead Books',
                'tahun_terbit' => 2003,
                'kategori' => 'Historical Fiction',
                'stok' => 3,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg',
                'deskripsi' => 'A powerful story of friendship, betrayal, and redemption set against the backdrop of Afghanistan. An unforgettable tale of love and sacrifice.',
                'rating' => 4.7,
                'is_featured' => false,
                'returned_at' => Carbon::now()->subMinutes(45),
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK014',
                'isbn' => '9780618640157',
                'judul' => 'Life of Pi',
                'pengarang' => 'Yann Martel',
                'penerbit' => 'Mariner Books',
                'tahun_terbit' => 2001,
                'kategori' => 'Adventure',
                'stok' => 2,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780618640157-L.jpg',
                'deskripsi' => 'A young Indian boy survives 227 days stranded on a lifeboat with a Bengal tiger. A profound meditation on faith, survival, and storytelling.',
                'rating' => 4.1,
                'is_featured' => false,
                'returned_at' => Carbon::now()->subHours(3),
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK015',
                'isbn' => '9781594489501',
                'judul' => 'The Book Thief',
                'pengarang' => 'Markus Zusak',
                'penerbit' => 'Alfred A. Knopf',
                'tahun_terbit' => 2005,
                'kategori' => 'Historical Fiction',
                'stok' => 1,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9781594489501-L.jpg',
                'deskripsi' => 'Death narrates the story of a young girl stealing books in Nazi Germany. A haunting tale of courage, love, and the power of words.',
                'rating' => 4.8,
                'is_featured' => false,
                'returned_at' => Carbon::now()->subHours(1),
                'waitlist_count' => 0,
            ],

            // === BUKU TERBARU (created_at recent) - 5 buku ===
            [
                'kode_buku' => 'BK016',
                'isbn' => '9781668001226',
                'judul' => 'Happy Place',
                'pengarang' => 'Emily Henry',
                'penerbit' => 'Berkley',
                'tahun_terbit' => 2023,
                'kategori' => 'Romance',
                'stok' => 5,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9781668001226-L.jpg',
                'deskripsi' => 'A couple who secretly broke up must pretend to still be together during their annual friend group vacation. Heartfelt contemporary romance.',
                'rating' => 4.4,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK017',
                'isbn' => '9780593597200',
                'judul' => 'Fourth Wing',
                'pengarang' => 'Rebecca Yarros',
                'penerbit' => 'Entangled Publishing',
                'tahun_terbit' => 2023,
                'kategori' => 'Fantasy',
                'stok' => 6,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780593597200-L.jpg',
                'deskripsi' => 'A young woman enters a brutal war college for dragon riders where survival is not guaranteed. Enemies-to-lovers romantasy with high stakes.',
                'rating' => 4.6,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK018',
                'isbn' => '9780593355213',
                'judul' => 'Tomorrow, and Tomorrow, and Tomorrow',
                'pengarang' => 'Gabrielle Zevin',
                'penerbit' => 'Alfred A. Knopf',
                'tahun_terbit' => 2022,
                'kategori' => 'Fiction',
                'stok' => 4,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780593355213-L.jpg',
                'deskripsi' => 'Two friends build video game empire together over 30 years while navigating love, betrayal, and art. A love letter to creativity and friendship.',
                'rating' => 4.5,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK019',
                'isbn' => '9780593450291',
                'judul' => 'Lessons in Chemistry',
                'pengarang' => 'Bonnie Garmus',
                'penerbit' => 'Doubleday',
                'tahun_terbit' => 2022,
                'kategori' => 'Fiction',
                'stok' => 3,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780593450291-L.jpg',
                'deskripsi' => 'A brilliant chemist in the 1960s becomes an unlikely TV cooking show star. A story about women in science, single motherhood, and defying expectations.',
                'rating' => 4.7,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK020',
                'isbn' => '9780593598245',
                'judul' => 'Holly',
                'pengarang' => 'Stephen King',
                'penerbit' => 'Scribner',
                'tahun_terbit' => 2023,
                'kategori' => 'Horror',
                'stok' => 4,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780593598245-L.jpg',
                'deskripsi' => 'Private detective Holly Gibney investigates the disappearance of a young girl in this gripping thriller. Classic King suspense and horror.',
                'rating' => 4.2,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],

            // === BUKU TAMBAHAN (variasi stok & kategori) - 5 buku ===
            [
                'kode_buku' => 'BK021',
                'isbn' => '9780553380163',
                'judul' => 'A Game of Thrones',
                'pengarang' => 'George R.R. Martin',
                'penerbit' => 'Bantam Books',
                'tahun_terbit' => 1996,
                'kategori' => 'Fantasy',
                'stok' => 7,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg',
                'deskripsi' => 'Noble families vie for control of the Iron Throne in a land where summers and winters last for years. Epic fantasy with political intrigue.',
                'rating' => 4.6,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK022',
                'isbn' => '9780544003415',
                'judul' => 'The Lord of the Rings',
                'pengarang' => 'J.R.R. Tolkien',
                'penerbit' => 'Mariner Books',
                'tahun_terbit' => 1954,
                'kategori' => 'Fantasy',
                'stok' => 5,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780544003415-L.jpg',
                'deskripsi' => 'A hobbit and his companions embark on a quest to destroy a powerful ring and save Middle-earth. The definitive fantasy epic.',
                'rating' => 4.9,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK023',
                'isbn' => '9780439136365',
                'judul' => 'Harry Potter and the Prisoner of Azkaban',
                'pengarang' => 'J.K. Rowling',
                'penerbit' => 'Scholastic',
                'tahun_terbit' => 1999,
                'kategori' => 'Fantasy',
                'stok' => 8,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780439136365-L.jpg',
                'deskripsi' => 'Harry\'s third year at Hogwarts brings a dangerous escaped prisoner and revelations about his past. The series turns darker and more complex.',
                'rating' => 4.8,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK024',
                'isbn' => '9780062315007',
                'judul' => 'The Alchemist',
                'pengarang' => 'Paulo Coelho',
                'penerbit' => 'HarperOne',
                'tahun_terbit' => 1988,
                'kategori' => 'Fiction',
                'stok' => 4,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg',
                'deskripsi' => 'A shepherd boy journeys to Egypt in search of treasure and discovers his true destiny. An inspirational fable about following your dreams.',
                'rating' => 4.3,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
            [
                'kode_buku' => 'BK025',
                'isbn' => '9780316769174',
                'judul' => '1984',
                'pengarang' => 'George Orwell',
                'penerbit' => 'Signet Classic',
                'tahun_terbit' => 1949,
                'kategori' => 'Dystopian',
                'stok' => 6,
                'cover' => 'https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg',
                'deskripsi' => 'In a totalitarian society, one man dares to rebel against Big Brother. A chilling vision of surveillance, thought control, and authoritarianism.',
                'rating' => 4.7,
                'is_featured' => false,
                'returned_at' => null,
                'waitlist_count' => 0,
            ],
        ];

        // Insert buku dengan timestamp berbeda untuk yang "terbaru"
        foreach ($books as $index => $book) {
            // Buku 16-20 adalah "terbaru" (created_at dalam 1 minggu terakhir)
            if ($index >= 15 && $index <= 19) {
                $createdAt = Carbon::now()->subDays(rand(1, 7));
            } else {
                $createdAt = Carbon::now()->subMonths(rand(1, 6));
            }

            Buku::create(array_merge($book, [
                'created_at' => $createdAt,
                'updated_at' => $createdAt,
            ]));
        }

        $this->command->info('✅ 25 buku berhasil ditambahkan dengan data realistis!');
    }
}
